### ISSUE TITLE
No show info from time to time

### ISSUE THREAD

**Issue by pepsonEL** [thomasgermain/vaillant-component#52] opened 2021-04-22 20:53 UTC
WHen i installed Multimatic by HACS i have a problem. After reboot HA show all data ok. But after some time not show data on entieties multimatic.  WHen i use old version by custom_components 1.5.0 b6 all works ok. Now still is a problem. After reboot HA again show all data and after some time again problem....

**Comment by thomasgermain** [comment] 2021-04-22 20:55
duplicate of #48

**Closed by thomasgermain** 2021-04-22 20:55 UTC
