### ISSUE TITLE
service fails to get token

### ISSUE THREAD

**Issue by colesadam** [thomasgermain/vaillant-component#165] opened 2022-11-19 14:55 UTC
Hi, still having lots of connectivity issues. Recently I've noticed that the vaillant app on android appears to be able to refresh but your service still can't connect via the API. This is the error at that point:

`pymultimatic.api.error.ApiError: Cannot get token at https://smart.vaillant.com/mobile/api/v4/account/authentication/v1/token/new, status: 401, response: <!doctype html><html lang="en"><head><title>HTTP Status 401 – Unauthorized</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 401 – Unauthorized</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Description</b> The request has not been applied because it lacks valid authentication credentials for the target resource.</p><hr class="line" /><h3>Apache Tomcat/mobilDIALOG-Live</h3></body></html>,payload: None`

Eventually it seems to work but obviously some failure in the authentication chain.

**Comment by AllStarzes** [comment] 2022-11-19 18:48
Same issue here 👍

**Comment by Zubredo** [comment] 2022-11-19 18:50
same issue here as well

**Comment by thomasgermain** [comment] 2022-11-19 19:02
Hello, 

Are you using a dedicated user for HA ?

Are you able to connect to multimatic app with this user ?

**Comment by h4de5** [comment] 2022-11-19 19:19
I do have a dedicated user, I can login in the app, but it seems I cannot control it in the app either :\ so most likely a vaillant issue ..

**Comment by switschel** [comment] 2022-11-19 20:14
I have same issue, getting 401 after 500 status codes the days before. Could it be that they changed something on their servers? App is able to connect, also using a dedicated user.

**Comment by thomasgermain** [comment] 2022-11-19 21:18
It sounds their server is unstable. I tried to connect to the application and one time out of tree, I can connect, otherwise it gives me an error.

I sent them a ticket, let's see

**Comment by marcodewaard** [comment] 2022-11-20 08:19
I'm also having issues pointing to an unstable API or (upcoming?) changes for a few days, or actually weeks. Haven't got any data since yesterday. 

`Unable to authenticate: Cannot get token at https://smart.vaillant.com/mobile/api/v4/account/authentication/v1/token/new, status: 401, response: <!doctype html><html lang="en"><head><title>HTTP Status 401 – Unauthorized</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 401 – Unauthorized</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Description</b> **The request has not been applied because it lacks valid authentication credentials for the target resource.**</p><hr class="line" /><h3>Apache Tomcat/mobilDIALOG-Live</h3></body></html>`

I've seen some `2022-11-20 07:54:47.427 ERROR (MainThread) [custom_components.multimatic.coordinator] Error requesting multimatic_gateway data: [Errno 104] Connection reset by peer` errors to.

The MultiMatic app works now, but it had issues yesterday and was giving maintenance warnings.

**Comment by linomas** [comment] 2022-11-20 09:51
Same Problem here. The App was down yesterday (2022-11-19). Now the Anroid-App is working, but the Multimatic integration is down since yesterday.

**Comment by thomasgermain** [comment] 2022-11-20 10:07
I can confirm the android app is not working properly. Just tried few times to login to the app with my HA user and I got this 
![Screenshot_2022-11-20-11-04-29-95_a23d235124f522f2f4eac702e62a32e9](https://user-images.githubusercontent.com/12560542/202896169-85ed3891-5fca-4568-a61c-64d404e62e88.jpg)

This is in french, it basically says: check your username and password.

Of course, credentials are correct

**Comment by sven055** [comment] 2022-11-20 10:36
I tried to create a new user account for HA and got this after I followed the link in the email....
![Vaillant](https://user-images.githubusercontent.com/60066796/202897346-05324ed8-340a-410b-849a-e3ecaf0e4b09.JPG)
During connection with the old credentials I got this in HA...
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.multimatic.config_flow
Source: custom_components/multimatic/config_flow.py:72
Integration: Multimatic (documentation, issues)
First occurred: 19. November 2022 um 15:42:21 (19 occurrences)
Last logged: 11:27:54

Unable to authenticate: Cannot get token at https://smart.vaillant.com/mobile/api/v4/account/authentication/v1/token/new, status: 401, response: <!doctype html><html lang="en"><head><title>HTTP Status 401 – Unauthorized</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 401 – Unauthorized</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Description</b> The request has not been applied because it lacks valid authentication credentials for the target resource.</p><hr class="line" /><h3>Apache Tomcat/mobilDIALOG-Live</h3></body></html>

**Comment by mprajsler** [comment] 2022-11-20 10:39
Hello can confirm this behaviour in my setup as well. Hope we ever see some local controll :-(

**Comment by mediaNen** [comment] 2022-11-20 11:09
Same for me, login through app works fine, but not able to login through hacs integration. I tried to delete and add the integration, but throws a 104 error when entering username and password.

**Comment by johanvh83** [comment] 2022-11-20 13:05
Same problem here. Multimatic application on my Android works but HA doesn't work anymore.

My log:
This error originated from a custom integration.

Logger: custom_components.multimatic.coordinator
Source: helpers/update_coordinator.py:182
Integration: Multimatic (documentation, issues)
First occurred: 1:55:13 PM (12 occurrences)
Last logged: 1:55:28 PM

Error requesting multimatic_holiday_mode data: [Errno 104] Connection reset by peer
Error requesting multimatic_hvac_status data: [Errno 104] Connection reset by peer
Error requesting multimatic_facility_detail data: [Errno 104] Connection reset by peer
Error requesting multimatic_gateway data: [Errno 104] Connection reset by peer
Error requesting multimatic_emf_reports data: [Errno 104] Connection reset by peer

**Comment by salzrat** [comment] 2022-11-20 13:39
I can report exactly the same behavior... Ios App works fine (yesterday it didn't), but multimatic integration doesn't get a token...

**Comment by GLehnhoff** [comment] 2022-11-20 16:15
Same problem, Vaillant-App works partly.

**Comment by simonbriers** [comment] 2022-11-21 02:13
Same issues here, hope it will get fixed, would not be the first time there are issues on the serverside. At this time, HA integration is still not functional.

**Comment by lecocqe** [comment] 2022-11-21 07:06
@thomasgermain , any news from vaillant ?
![image](https://user-images.githubusercontent.com/18657222/202986244-dac3135f-7932-4a25-a341-29f92d47f037.png)

**Comment by h4de5** [comment] 2022-11-21 10:20
Is there something we - as user of vaillant and your implementation - can do, in order to get your request a higher priority? You said you would create a ticket on their system - is there some way to upvote it? (I know I am dreaming here... but maybe..)

**Comment by thomasgermain** [comment] 2022-11-21 13:08
Ok so, I decompiled the last android APK and found out that there is a "new" header (not so new actually, but It apparently became mandatory) "Vaillant-Mobile-App".

Version https://github.com/thomasgermain/vaillant-component/releases/tag/1.12.10 should fix the issue

**Comment by mediaNen** [comment] 2022-11-21 13:12
Installed the update and now it works again, thank you @thomasgermain , great work!

**Comment by marcodewaard** [comment] 2022-11-21 13:21
👏 Works again! Thanks @thomasgermain

**Comment by AllStarzes** [comment] 2022-11-21 13:34
Yes. Thank u so much. Works again.
I see the developer has fixed the app from vaillant. You can now login in to the app.

**Comment by switschel** [comment] 2022-11-21 13:41
And now the servers are going down :-)
pymultimatic.api.error.ApiError: Cannot get token at https://smart.vaillant.com/mobile/api/v4/account/authentication/v1/token/new, status: 503, response: Service Unavailable,payload: None

**Comment by salzrat** [comment] 2022-11-21 18:51
The problem came back :(
Maybe one is blocked if two many queries are done? (here with the same authentication failure)

**Comment by salzrat** [comment] 2022-11-21 18:56
Ok, sorry - I had installed 1.12.10 manually, but it seems HACS overwrote it again after a restart. Now that the update is also available via HACS and I installed it, it started working again...

**Comment by johanvh83** [comment] 2022-11-21 19:04
Just installed 1.12.10. Can confirm that it works again.
Hopefully it remains like this.
MANY THANKS THOMAS !

**Comment by thomasgermain** [comment] 2022-11-21 19:47
I'm quite happy to close this one :)

**Closed by thomasgermain** 2022-11-21 19:47 UTC

**Comment by colesadam** [comment] 2022-11-21 19:55
👍
