### ISSUE TITLE
Vaillant integration is not fully working after new vaillant upgrade to new application "Myvaillant"

### ISSUE THREAD

**Issue by okikaHA** [thomasgermain/vaillant-component#267] opened 2024-02-06 06:08 UTC
Vaillant integration is not working after new vaillant upgrade to new application "Myvaillant". Do you know about this problem please ? Thx.

**Comment by okikaHA** [comment] 2024-02-06 06:29
After reintegration, 5 subjects are missing... but the main ones... heating, hot water, circulation, outside temperature... maybe they just renamed it? ....

**Comment by jackqu0** [comment] 2024-02-06 12:42
I am also being badgered to upgrade the app, and to be honest it looks much improved. But having just spend a bunch of time setting up this integration I am waiting for confirmation that it continues to work with the new app/gateway firmware. Is there a plan?

**Comment by okikaHA** [comment] 2024-02-06 13:56
Hello, I contacted vaillant company, and they said me, that all users will be forced on upgrade and new app, old solution and old app will be canceled at the end of April. Downgrade is it not possible. So it is not good information and update of integration will be necessary.

**Comment by GLehnhoff** [comment] 2024-02-12 17:08
Same problem. I upgraded today and the integration seems not to work anymore. Before I do anything, I will wait for a statement from the developer.

**Comment by GLehnhoff** [comment] 2024-02-12 17:10
This issue might be a duplicate of https://github.com/thomasgermain/vaillant-component/issues/260

**Comment by mike4001** [comment] 2024-02-20 11:48
Hi

I found this one - https://github.com/signalkraft/mypyllant-component

Couldn't test it though, but maybe its working.

**Comment by pepsonEL** [comment] 2024-02-20 12:26
> Hi
> 
> I found this one - https://github.com/signalkraft/mypyllant-component
> 
> Couldn't test it though, but maybe its working.

Yes it works very good with new app myVaillant.

**Comment by ralphbk** [comment] 2024-03-12 15:00
I see no activity from @thomasgermain since October 2023. Has anyone heard from him since then? Can we assume that the vaillant-component is dead? Or at least will be by 30.3.2024, when Vaillant kill the old API.

It appears we should be moving to:
- https://community.home-assistant.io/t/myvaillant-integration/542610
AKA:
 - https://github.com/signalkraft/mypyllant-component

Right?

**Comment by mike4001** [comment] 2024-03-12 15:31
> I see no activity from @thomasgermain since October 2023. Has anyone heard from him since then? Can we assume that the vaillant-component is dead? Or at least will be by 30.3.2024, when Vaillant kill the old API.
> 
> It appears we should be moving to:
> 
> * https://community.home-assistant.io/t/myvaillant-integration/542610
>   AKA:
> * https://github.com/signalkraft/mypyllant-component
> 
> Right?

This is basically correct.

Unless @thomasgermain rewrites his integration it will seize to function in 2,5 weeks.

The mypyllant integration is actively maintained and working great.

**Comment by thomasgermain** [comment] 2024-03-19 15:58
Hello,

I made a communication here: https://community.home-assistant.io/t/vaillant-multimatic-integration/87240/562.

This integration will work until you migrate, after that you will have to switch to the new integration (it requires some maintenance, since the system is quite different from multimatic).

For now, ambisense it not yet integrated, but I'm busy with @signalkraft

**Closed by thomasgermain** 2024-03-19 15:58 UTC
